### ISSUE TITLE
Missing files: test_dpm_unary/head/imgidx_0001.mat

### ISSUE THREAD

**Issue by leexulong** [leonid-pishchulin/partapp#1]
hi, is there some mat files are missing, or I did some wrong configurations? The following is the command and output using the "test code".

$ ../run_partapp.sh --expopt ./expopt/exp-code-test-local-app-model.txt --head_detect_dpm --part_detect_dpm --find_obj 
MATLAB:I18n:LocaleDatabaseNotFound - Cannot find the MATLAB locale database. The MATLAB process default locale is set to "en_US.US-ASCII".
multi-component version
argc: 6
argv[0]: ../bin/Release/partapp
reading command line parameters
initializing from ./expopt/exp-code-test-local-app-model.txt
part configuration: ./expopt/part_conf_22_parts.txt
classifier parameters: ./expopt/abcparams_rounds500_dense05_2000.txt
set class_dir to: ./log_dir//exp-code-test-local-app-model/class
set scoregrid_dir to: ./log_dir//exp-code-test-local-app-model/test_scoregrid
set scoregrid_train_dir to: ./log_dir//exp-code-test-local-app-model/train_scoregrid
set part_marginals_dir to: ./log_dir//exp-code-test-local-app-model/part_marginals
set test_dpm_unary_dir to: ./log_dir//exp-code-test-local-app-model/test_dpm_unary
set dpm_model_dir to: ./log_dir//exp-code-test-local-app-model/dpm_model
set test_dpm_torso_dir to: ./log_dir//exp-code-test-local-app-model/test_dpm_unary/torso
set mix_dir to: ./log_dir//exp-code-test-local-app-model/part_marginals
set pred_data_dir to: ./log_dir//exp-code-test-local-app-model/pred_data
set pred_data_test_dir to: ./log_dir//exp-code-test-local-app-model/pred_data_test
set poselet_resp_val_dir to: ./log_dir//exp-code-test-local-app-model/resp_train
set poselet_resp_test_dir to: ./log_dir//exp-code-test-local-app-model/resp_test
set spatial_dir to: ./log_dir//exp-code-test-local-app-model/spatial
set dai_samples_dir to: ./log_dir//exp-code-test-local-app-model/part_marginals_samples

loading training data from train.al
AnnotationList::loadXML( train.al )
Finished AnnotationList::load( train.al )
loaded 1 real training images
loaded 0 reshaped training images

loading test data from code_test.al
AnnotationList::loadXML( code_test.al )
Finished AnnotationList::load( code_test.al )
qsWindowParamFile: ./log_dir//exp-code-test-local-app-model/class/window_param.txt

loading window parameters from ./log_dir//exp-code-test-local-app-model/class/window_param.txt
saving Matlab visualization parameters in:  ./log_dir//exp-code-test-local-app-model/params_mat
partdetect_dpm_all()
imgidx: 0
runMatlabCode()
qsCommandLine: run_partdetect_dpm_all.sh /BS/opt/local/MATLAB_Compiler_Runtime/v81/ 1 ./images/im1318-rescaled.png 22 ./log_dir//exp-code-test-local-app-model/dpm_model ./log_dir//exp-code-test-local-app-model/test_dpm_unary 100 1 2 1 1
state: 0
done
partdetect_dpm()
imgidx: 0
runMatlabCode()
qsCommandLine: run_partdetect_dpm.sh /BS/opt/local/MATLAB_Compiler_Runtime/v81/ 1 ./images/im1318-rescaled.png ./log_dir//exp-code-test-local-app-model/dpm_model/head/head_final.mat ./log_dir//exp-code-test-local-app-model/test_dpm_unary/head 100 1 2 1 1
state: 0
done
findObjectDataset
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_1_2.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_1_2.mat
processing images 0 to 0
bFindObjectRot: 1
processing image 0
bRecomputeScoreGrid: 1
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part0.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part1.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part2.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part3.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part4.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part5.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part6.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part7.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part8.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part9.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part10.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part11.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part12.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part13.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part14.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part15.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part16.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part17.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part18.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part19.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part20.class
loading classifier from ./log_dir//exp-code-test-local-app-model/class/part21.class
computing features on image 0
feature type: SHAPEv5
desc_step: 8, desc_size: 18, window_step: 4, grid_step: 2
scale: 1, rotation: -176.25, flip: 0
scale: 1, rotation: -168.75, flip: 0
scale: 1, rotation: -161.25, flip: 0
scale: 1, rotation: -153.75, flip: 0
scale: 1, rotation: -146.25, flip: 0
scale: 1, rotation: -138.75, flip: 0
scale: 1, rotation: -131.25, flip: 0
scale: 1, rotation: -123.75, flip: 0
scale: 1, rotation: -116.25, flip: 0
scale: 1, rotation: -108.75, flip: 0
scale: 1, rotation: -101.25, flip: 0
scale: 1, rotation: -93.75, flip: 0
scale: 1, rotation: -86.25, flip: 0
scale: 1, rotation: -78.75, flip: 0
scale: 1, rotation: -71.25, flip: 0
scale: 1, rotation: -63.75, flip: 0
scale: 1, rotation: -56.25, flip: 0
scale: 1, rotation: -48.75, flip: 0
scale: 1, rotation: -41.25, flip: 0
scale: 1, rotation: -33.75, flip: 0
scale: 1, rotation: -26.25, flip: 0
scale: 1, rotation: -18.75, flip: 0
scale: 1, rotation: -11.25, flip: 0
scale: 1, rotation: -3.75, flip: 0
scale: 1, rotation: 3.75, flip: 0
scale: 1, rotation: 11.25, flip: 0
scale: 1, rotation: 18.75, flip: 0
scale: 1, rotation: 26.25, flip: 0
scale: 1, rotation: 33.75, flip: 0
scale: 1, rotation: 41.25, flip: 0
scale: 1, rotation: 48.75, flip: 0
scale: 1, rotation: 56.25, flip: 0
scale: 1, rotation: 63.75, flip: 0
scale: 1, rotation: 71.25, flip: 0
scale: 1, rotation: 78.75, flip: 0
scale: 1, rotation: 86.25, flip: 0
scale: 1, rotation: 93.75, flip: 0
scale: 1, rotation: 101.25, flip: 0
scale: 1, rotation: 108.75, flip: 0
scale: 1, rotation: 116.25, flip: 0
scale: 1, rotation: 123.75, flip: 0
scale: 1, rotation: 131.25, flip: 0
scale: 1, rotation: 138.75, flip: 0
scale: 1, rotation: 146.25, flip: 0
scale: 1, rotation: 153.75, flip: 0
scale: 1, rotation: 161.25, flip: 0
scale: 1, rotation: 168.75, flip: 0
scale: 1, rotation: 176.25, flip: 0
bSaveScoreGrid: 0
findObjectImageRotJoints
nJoints: 21
nParts: 22
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_1_2.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_1_2.mat
offset_p: 0
1.3989e-15 25.7758 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_2_3.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_2_3.mat
offset_p: 1
0 0 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_3_4.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_3_4.mat
offset_p: 2
1.36723e-15 24.5681 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_4_5.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_4_5.mat
offset_p: 3
0 0 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_5_11.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_5_11.mat
offset_p: 4
-9.38543 32.5793 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_6_11.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_6_11.mat
offset_p: 5
9.38291 32.5874 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_7_6.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_7_6.mat
offset_p: 6
0 0 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_8_7.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_8_7.mat
offset_p: 7
1.37087e-15 24.5678 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_9_8.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_9_8.mat
offset_p: 8
0 0 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_10_9.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_10_9.mat
offset_p: 9
1.42945e-15 25.7751 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_12_11.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_12_11.mat
offset_p: 10
-1.72665e-15 -32.5779 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_13_14.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_13_14.mat
offset_p: 11
7.4062e-16 14.9367 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_14_15.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_14_15.mat
offset_p: 12
0 0 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_15_16.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_15_16.mat
offset_p: 13
8.61195e-16 16.8546 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_16_17.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_16_17.mat
offset_p: 14
0 0 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_17_11.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_17_11.mat
offset_p: 15
-16.4915 -32.5904 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_18_11.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_18_11.mat
offset_p: 16
16.4969 -32.5903 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_19_18.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_19_18.mat
offset_p: 17
0 0 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_20_19.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_20_19.mat
offset_p: 18
8.49111e-16 16.8536 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_21_20.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_21_20.mat
offset_p: 19
0 0 
loading ./log_dir//exp-code-test-local-app-model/spatial/joint_22_21.mat
loading rot_mean from ./log_dir//exp-code-test-local-app-model/spatial/joint_22_21.mat
offset_p: 20
7.47674e-16 14.9402 
covariance matrix of the joint: 
12.3956 0.296467 
0.296467 23.0708 
covariance matrix of the joint: 
13.2411 0.297365 
0.297365 23.5199 
covariance matrix of the joint: 
10.148 -0.942362 
-0.942362 17.678 
covariance matrix of the joint: 
10.1931 -0.891827 
-0.891827 17.3071 
covariance matrix of the joint: 
26.4824 2.39753 
2.39753 21.1043 
covariance matrix of the joint: 
25.6625 -2.48419 
-2.48419 21.0863 
covariance matrix of the joint: 
9.70599 0.74189 
0.74189 16.989 
covariance matrix of the joint: 
10.4187 1.13974 
1.13974 17.4068 
covariance matrix of the joint: 
12.3888 -0.166118 
-0.166118 23.2158 
covariance matrix of the joint: 
12.9155 -0.458978 
-0.458978 22.9551 
covariance matrix of the joint: 
34.0036 -0.00527293 
-0.00527293 26.3887 
covariance matrix of the joint: 
11.511 0.0718329 
0.0718329 12.2119 
covariance matrix of the joint: 
11.3259 -0.246556 
-0.246556 12.5098 
covariance matrix of the joint: 
8.10104 -1.07968 
-1.07968 12.3967 
covariance matrix of the joint: 
8.32216 -1.16104 
-1.16104 12.1638 
covariance matrix of the joint: 
72.2971 -4.29126 
-4.29126 44.024 
covariance matrix of the joint: 
71.8626 4.56075 
4.56075 43.6546 
covariance matrix of the joint: 
8.0834 1.18686 
1.18686 12.3941 
covariance matrix of the joint: 
8.23839 1.54125 
1.54125 12.4938 
covariance matrix of the joint: 
11.1426 0.1425 
0.1425 12.8695 
covariance matrix of the joint: 
11.9965 0.326545 
0.326545 12.0245 
nParts: 22
nScales: 1
nRotations: 48
img_height: 264
img_width: 129

rootpart_idx: 10

loadDPMScoreGrid()
load ./log_dir//exp-code-test-local-app-model/test_dpm_unary/torso/imgidx_0001.mat

getTorsoPosPriorParams()
0.508754
26.924
179.857
226.109

addDPMScore()
pidx: 10
dpm_weight: 1
bRot: 0

AddDPMscoreCell()
dpm_weight: 1

imgidx: 0; pidx: 11
loadDPMScoreGrid()
load ./log_dir//exp-code-test-local-app-model/test_dpm_unary/head/imgidx_0001.mat
partapp: objectdetect_icps.cpp:555: void object_detect::loadDPMScoreGrid(QString, int, std::vector<boost::multi_array<float, 2ul, std::allocator<float> >, std::allocator<boost::multi_array<float, 2ul, std::allocator<float> > > >&, bool): Assertion `filesys::check_file(qsScoreGridName)' failed.
Aborted (core dumped)

**Comment by leonid-pishchulin** [comment]
files were not missing, but that's the dpm part detections were not computed due to matlab failure. Check if the the machine you are running at has enough memory. I added an assert which checks if the dpm part detections were computed.
