### ISSUE TITLE
About the compiling

### ISSUE THREAD

**Issue by HeGaoYuan** [leonid-pishchulin/partapp#2]
Hi,
    I am very interesting in your project. But I have some trouble in compiling.
    I don't understand the step 4 in the compiling, **Point to your MCR by editing the file src/libs/libPrediction/matlab_runtime.h**. Can you tell me what should I edit the file in details?
    Thank you very much! Looking forward to your reply.
    Best wishes!

**Comment by leonid-pishchulin** [comment]
you should set the path to your matlab run-time environment
#define MATLAB_RUNTIME "/path/to/matlab_runtime"

**Comment by leonid-pishchulin** [comment]
I would recommend to look into our most recent state-of-the-art model
http://pose.mpi-inf.mpg.de/
that achieves significantly better results compared to partapp
